# docker compose build - используем эту команду, если меняли что-то в Dockerfile
# docker compose up - если изменили только docker-compose


services:
  db:
    image: postgres:15
    container_name: goida_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file: # Файл с переменными окружения (Вместо environment)
      - .env-non-dev



  shop:
    image: shop_image
    build:
      context: .
    container_name: shop_app
    env_file:
      - .env-non-dev
    depends_on: # Запускаем только после запуска БД и Redis (depends on = зависит от)
      - db

    # Если не работает эта команда, используйт закомментированную или напиши мне
    command: ["/shop/docker/app.sh"]
    # command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000
volumes:
  postgresdata:
  grafanadata:
  prometheusdata:





      

